apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: multi-k8s
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker
    context: tracker
    ko:
      labels:
        org.opencontainers.image.licenses: Apache-2.0
        org.opencontainers.image.revision: "{{.GITHUB_SHA}}"
        org.opencontainers.image.source: "{{.GITHUB_SERVER_URL}}/{{.GITHUB_REPOSITORY}}"
    platforms:
      - linux/amd64

deploy:
  kubectl:
    defaultNamespace: run-tracker
    manifests:
    - manifests/ns-rev.yaml
    - manifests/deploy-svc-1.yaml
    - manifests/svc-1.yaml
    - manifests/deploy-svc-2.yaml
    - manifests/svc-2.yaml
    - manifests/deploy-svc-3.yaml
    - manifests/svc-3.yaml
    - manifests/deploy-svc-4.yaml
    - manifests/svc-4.yaml
