apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: multi-k8s
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker
    context: tracker
    ko:
      labels:
        org.opencontainers.image.licenses: Apache-2.0
        org.opencontainers.image.revision: "{{.GITHUB_SHA}}"
        org.opencontainers.image.source: "{{.GITHUB_SERVER_URL}}/{{.GITHUB_REPOSITORY}}"
      dependencies:
        paths:
          - kodata
          - .
    platforms:
      - linux/amd64

deploy:
  kustomize:
    paths: ["manifests/examples/locality"]
    
  statusCheck: true