apiVersion: v1
kind: Service
metadata:
  name: svc-1-v2
spec: 
  type: ClusterIP
  selector:
    app: tracker
    svc: svc-1
    ver: v2
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: tcp
    port: 8008
    targetPort: 8008
