
namespace: run-tracker

images:
  - name: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker
    newTag: "50123e7"

resources:
  - ../../base
  - ../../redis
  - ../../deploy-affinity
  - ../../service

patches:
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer   
    target:
      kind: Service
      name: svc-1