
#
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: svc-1-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: svc-1-vs
spec:
  hosts:
  - "*"
  gateways:
  - svc-1-gateway
  http:
  - route:
    - destination:
        host: svc-1.run-tracker.svc.cluster.local
        port:
          number: 8000

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: svc-1-dr
spec:
  host: svc-1.run-tracker.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: ap-southeast-1/ap-southeast-1a/*
          to:
            "ap-southeast-1/ap-southeast-1a/*": 100
        - from: ap-southeast-1/ap-southeast-1b/*
          to:
            "ap-southeast-1/ap-southeast-1b/*": 100
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 1m



---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: svc-2-dr
spec:
  host: svc-2.run-tracker.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: ap-southeast-1/ap-southeast-1a/*
          to:
            "ap-southeast-1/ap-southeast-1a/*": 100
        - from: ap-southeast-1/ap-southeast-1b/*
          to:
            "ap-southeast-1/ap-southeast-1b/*": 100
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 1m

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: svc-3-dr
spec:
  host: svc-3.run-tracker.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: ap-southeast-1/ap-southeast-1a/*
          to:
            "ap-southeast-1/ap-southeast-1a/*": 100
        - from: ap-southeast-1/ap-southeast-1b/*
          to:
            "ap-southeast-1/ap-southeast-1b/*": 100
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 1m

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: svc-4-dr
spec:
  host: svc-4.run-tracker.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: ap-southeast-1/ap-southeast-1a/*
          to:
            "ap-southeast-1/ap-southeast-1a/*": 100
        - from: ap-southeast-1/ap-southeast-1b/*
          to:
            "ap-southeast-1/ap-southeast-1b/*": 100
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 1m