apiVersion: apps/v1
kind: Deployment 
metadata:
  name: tracker-svc-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracker
      svc: svc-2
  template:
    metadata:
      labels: 
        app: tracker
        svc: svc-2
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: tracker
        image:  us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker
        imagePullPolicy: "Always"
        env:
          - name: POD_NAME
            valueFrom: 
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom: 
              fieldRef:
                fieldPath: metadata.name
          - name: NEXT_CALL
            value: http://svc-3:8000/trip/pod
        ports:
          - name: http
            containerPort: 8000
        resources:
          requests: 
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi