apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracker-sa
  namespace: run-tracker

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tracker-node-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- kind: ServiceAccount
  name: default
  namespace: run-tracker