apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracker-sa


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tracker-role
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "pods", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tracker-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tracker-role
subjects:
- kind: ServiceAccount
  name: tracker-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tracker-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "pods", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tracker-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tracker-clusterrole
subjects:
- kind: ServiceAccount
  name: tracker-sa
  namespace: run-tracker
