apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    addon.kops.k8s.io/name: gcp-cloud-controller.addons.k8s.io
    k8s-addon: gcp-cloud-controller.addons.k8s.io
  name: cloud-controller-manager
  namespace: kube-system