apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: golang-storage
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  network: default

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: podpvc2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: golang-storage
  resources:
    requests:
      storage: 1Ti