apiVersion: tracker.tod.cc4i.xyz/v1
kind: TrackerTop
metadata:
  name: trackertop-sample
spec:
  where: "run-test"
  trackers:
    - name: front-svc1
      image: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker:v0.11-2-gc4256bd-dirty
      version: v1
      replicas: 1
  graph: 
    - name: front-svc1
  redis:
    image: "redis:alpine"
    name: "redis-4tracker"
    host: "redis-4tracker"
    port: 6379