apiVersion: tracker.tod.cc4i.xyz/v1
kind: TrackerTop
metadata:
  name: trackertop-sample
spec:
  where: "run-test"
  trackers:
    - name: front-svc1
      image: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker:v0.11-15-g19905f0-dirty
      version: v1
      replicas: 1
      servingType: LoadBalancer
    - name: backend-svc10
      image: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker:v0.11-15-g19905f0-dirty
      version: v1
      replicas: 1
    - name: backend-svc11
      image: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker:v0.11-15-g19905f0-dirty
      version: v1
      replicas: 1
    - name: backend-svc20
      image: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker:v0.11-15-g19905f0-dirty
      version: v1
      replicas: 1
    - name: backend-svc21
      image: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker:v0.11-15-g19905f0-dirty
      version: v1
      replicas: 1
  graph:
    front-svc1:
      name: "front-svc1"
      downstream:
        - "backend-svc10"
        - "backend-svc11"
    backend-svc10:
      name: "backend-svc10"
      upstream: "front-svc1"
      downstream:
        - "backend-svc20"
        - "backend-svc21"
    
  redis:
    image: "redis:alpine"
    name: "redis-4tracker"
    host: "redis-4tracker"
    port: 6379