apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: multi-k8s
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/tracker
    context: tracker
    ko:
      labels:
        org.opencontainers.image.licenses: Apache-2.0
        org.opencontainers.image.revision: "{{.GITHUB_SHA}}"
        org.opencontainers.image.source: "{{.GITHUB_SERVER_URL}}/{{.GITHUB_REPOSITORY}}"
      dependencies:
        paths:
          - kodata
          - ks
          - trip
          - .
    platforms:
      - linux/amd64

deploy:
  kustomize:
    paths: 
      - ./manifests/examples/locality/
  #   buildArgs:
  #     - "--load-restrictor LoadRestrictionsNone"
  # kubectl:
  #   manifests:
  #     - manifests/base/ns-rev.yaml
  #     - manifests/base/service-account.yaml
  #     - manifests/deploy/deploy-svc-1.yaml
  #     - manifests/service/svc-1.yaml
  #     - manifests/deploy/deploy-svc-2.yaml
  #     - manifests/service/svc-2.yaml
  #     - manifests/deploy/deploy-svc-3.yaml
  #     - manifests/service/svc-3.yaml
  #     - manifests/deploy/deploy-svc-4.yaml
  #     - manifests/service/svc-4.yaml
  statusCheck: true

profiles:
  - name: aws
    deploy:
      kustomize:
        paths:
          - ./manifests/examples/locality/aws/