# permissions for end users to view trackertops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trackertop-viewer-role
rules:
- apiGroups:
  - tracker.tod.cc4i.xyz
  resources:
  - trackertops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tracker.tod.cc4i.xyz
  resources:
  - trackertops/status
  verbs:
  - get
